curl -X GET "https://api.live.bilibili.com/xlive/web-room/v1/index/getDanmuInfo?id=24779526&type=0&web_location=444.8&w_rid=a800b5b28ec0fcd6392de3de049bdd6c&wts=1751075873" \
  -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0" \
  -H "Referer: https://live.bilibili.com" \
  -H "Cookie: $Cookie"

# Error response:
# {
#   "code": -352,
#   "message": "-352",
#   "ttl": 1
# }

### Get the WEB public key for encryption is worked on the 

curl -X GET "https://api.bilibili.com/x/web-interface/nav" \
  -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0" \
  -H "Referer: https://live.bilibili.com" \
  -H "Cookie: $Cookie"